INSERT INTO INSTRUMENT_PRICE_MODIFIER VALUES
(1,'INSTRUMENT1',1.00);
INSERT INTO INSTRUMENT_PRICE_MODIFIER VALUES
(2,'INSTRUMENT2',1.00);
INSERT INTO INSTRUMENT_PRICE_MODIFIER VALUES
(3,'INSTRUMENT3',1.00);